pipeline {
    agent any

    tools {
        maven "maven_home"
        jdk "Jdk_home"
    }

    stages {
        stage('Initialize') {
            steps {
                echo "M2_HOME = ${env.M2_HOME}"
                echo "JAVA_HOME = ${env.JAVA_HOME}"
                echo "PATH = ${env.M2_HOME}\\bin;${env.JAVA_HOME}\\bin;${env.PATH}"
            }
        }
        stage('Build') {
            steps {
                dir("C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Pipeline_demo\\my-app") {
                    bat 'mvn -B -DskipTests clean package'
                }
            }
        }
    }
    post {
        always {
            junit(
                allowEmptyResults: true,
                testResults: '*/test-reports/*.xml'
            )
        }
    }
}
